version: '3.2'
services:
  notebooks:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        PORT: ${PORT:-51000}
    volumes:
      - ${PWD}/src:/home/jupyter/src
      - ${PWD}/notebooks:/home/jupyter/notebooks
      - ${PWD}/scratch:/home/jupyter/scratch
      - ${PWD}/data:/home/jupyter/data:ro
    ports:
      - ${PORT:-51000}